name: linter-test

on: 
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs: 
  super-lint:
    name: lint code base
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Run lint code
      uses: github/super-linter@v3
      env: 
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
